name: Go CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=30m
  
  
  build:
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Install dependencies
        run: go mod tidy
      
      - name: Run Go Vulnerability Scanner
        uses: debug-ing/go-vuln-scanner@v1.0.0

      - name: Go format check
        run: go fmt ./...
    
      - name: Go vet
        run: go vet ./...

      - name: Run golint
        run: golint ./...

      - name: Build project
        run: make build